CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

insert into users (id, name) values (1, 'user1');
insert into users (id, name) values (2, 'user2');